---
# Default cf-deployment deploys a (mostly) HA configuration.
# Use this override to only deploy single instance of each job,
# in a single Availability Zone.
- type: replace
  path: /instance_groups/name=all-in-one-1/instances
  value: 1
# - type: replace
#   path: /instance_groups/name=database/instances
#   value: 1
# - type: replace
#   path: /instance_groups/name=consul/instances
#   value: 1
# - type: replace
#   path: /instance_groups/name=nats/instances
#   value: 1
# - type: replace
#   path: /instance_groups/name=diego-api/instances
#   value: 1
# - type: replace
#   path: /instance_groups/name=uaa/instances
#   value: 1
# - type: replace
#   path: /instance_groups/name=all-in-one-4/instances
#   value: 1
# - type: replace
#   path: /instance_groups/name=all-in-one-5/instances
#   value: 1
# - type: replace
#   path: /instance_groups/name=all-in-one-3/instances
#   value: 1
- type: replace
  path: /instance_groups/name=all-in-one-2/instances
  value: 1
# - type: replace
#   path: /instance_groups/name=all-in-one-2/instances
#   value: 1
# - type: replace
#   path: /instance_groups/name=adapter/instances
#   value: 1
# - type: replace
#   path: /instance_groups/name=all-in-one-4/instances
#   value: 1
# - type: replace
#   path: /instance_groups/name=all-in-one-6/instances
#   value: 1
# - type: replace
#   path: /instance_groups/name=all-in-one-3/instances
#   value: 1

- type: replace
  path: /instance_groups/name=all-in-one-1/azs
  value: [ z1 ]
# - type: replace
#   path: /instance_groups/name=database/azs
#   value: [ z1 ]
# - type: replace
#   path: /instance_groups/name=nats/azs
#   value: [ z1 ]
# - type: replace
#   path: /instance_groups/name=diego-api/azs
#   value: [ z1 ]
# - type: replace
#   path: /instance_groups/name=uaa/azs
#   value: [ z1 ]
# - type: replace
#   path: /instance_groups/name=consul/azs
#   value: [ z1 ]
# - type: replace
#   path: /instance_groups/name=all-in-one-4/azs
#   value: [ z1 ]
# - type: replace
#   path: /instance_groups/name=all-in-one-5/azs
#   value: [ z1 ]
# - type: replace
#   path: /instance_groups/name=all-in-one-3/azs
#   value: [ z1 ]
- type: replace
  path: /instance_groups/name=all-in-one-2/azs
  value: [ z1 ]
# - type: replace
#   path: /instance_groups/name=all-in-one-2/azs
#   value: [ z1 ]
# - type: replace
#   path: /instance_groups/name=adapter/azs
#   value: [ z1 ]
# - type: replace
#   path: /instance_groups/name=all-in-one-4/azs
#   value: [ z1 ]
# - type: replace
#   path: /instance_groups/name=all-in-one-6/azs
#   value: [ z1 ]
# - type: replace
#   path: /instance_groups/name=all-in-one-3/azs
#   value: [ z1 ]
