- type: replace
  path: /instance_groups/name=all-in-one-2/jobs/name=cloud_controller_ng/properties/cc/default_app_memory?
  value: 128

- type: replace
  path: /instance_groups/name=all-in-one-1/vm_type
  value: small
# - type: replace
#   path: /instance_groups/name=database/vm_type
#   value: small
# - type: replace
#   path: /instance_groups/name=consul/vm_type
#   value: small
# - type: replace
#   path: /instance_groups/name=nats/vm_type
#   value: small
# - type: replace
#   path: /instance_groups/name=diego-api/vm_type
#   value: small
# - type: replace
#   path: /instance_groups/name=uaa/vm_type
#   value: small
# - type: replace
#   path: /instance_groups/name=all-in-one-4/vm_type
#   value: small
# - type: replace
#   path: /instance_groups/name=all-in-one-5/vm_type
#   value: small
# - type: replace
#   path: /instance_groups/name=all-in-one-3/vm_type
#   value: small
- type: replace
  path: /instance_groups/name=all-in-one-2/vm_type
  value: small
# - type: replace
#   path: /instance_groups/name=all-in-one-2/vm_type
#   value: small
# - type: replace
#   path: /instance_groups/name=adapter/vm_type
#   value: small
# - type: replace
#   path: /instance_groups/name=all-in-one-4/vm_type
#   value: small
# - type: replace
#   path: /instance_groups/name=all-in-one-6/vm_type
#   value: small
# - type: replace
#   path: /instance_groups/name=all-in-one-3/vm_type
#   value: small
