
# ----- Replace the properties for the container service providers.
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/diego/rep/use_vcontainer
  value: true

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=vcontainer/properties/diego/vcontainer/container_service_provider?
  value: "((container_service_provider))" # garden, aws or azure

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=vcontainer/properties/diego/vcontainer/smb_proxy?
  value:
    ip: "((smb_proxy_ip))"
    port: "((smb_proxy_port))"

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=vcontainer/properties/diego/vcontainer/azure_container_provider_cfg?
  value:
    container_id: "((client_id))"
    container_secret: "((client_secret))"
    optional_param_1: "((tenant_id))"
    location: "((aci_location))"
    subscription_id: "((subscription_id))"
    storage_id: "((aci_storage_id))"
    storage_secret: "((aci_storage_secret))"

- type: replace
  path: /releases/name=diego
  value:
    url: https://andliuonlinefiles.blob.core.windows.net/cf-private-releases/diego-release-vcontainer.tgz
    version: 2.6.0+dev.1526885702
    sha1: 5f75aa568ee14a9e4dc30ea08a95471e7982b19d